import type { DrugSummary } from "./types";

export const mockDrugs: DrugSummary[] = [
  {
    id: "fluoxetine",
    name: "Fluoxetine",
    primaryUse: "Major depressive disorder",
    otherUses: ["Panic disorder", "Bulimia nervosa", "Obsessive-compulsive disorder", "Premenstrual dysphoric disorder"],
    leastResearched: { dimension: "Race", group: "Black participants" },
    score: 62,
    tier: "Developing",
    components: { age: 71, sex: 79, race: 38 },
    trialCount: 128,
    participantCount: 28410,
    updatedAt: "2025-05-14",
  },
  {
    id: "metformin",
    name: "Metformin",
    primaryUse: "Type 2 diabetes",
    otherUses: ["Prediabetes", "Polycystic ovary syndrome", "Gestational diabetes"],
    leastResearched: { dimension: "Race", group: "Indigenous participants" },
    score: 78,
    tier: "Strong",
    components: { age: 75, sex: 88, race: 69 },
    trialCount: 246,
    participantCount: 71830,
    updatedAt: "2025-05-14",
  },
  {
    id: "adalimumab",
    name: "Adalimumab",
    primaryUse: "Rheumatoid arthritis",
    otherUses: ["Crohn’s disease", "Plaque psoriasis", "Ulcerative colitis", "Psoriatic arthritis", "Hidradenitis suppurativa"],
    leastResearched: { dimension: "Age", group: "Adults 65 and older" },
    score: 70,
    tier: "Developing",
    components: { age: 46, sex: 89, race: 75 },
    trialCount: 94,
    participantCount: 22160,
    updatedAt: "2025-05-13",
  },
  {
    id: "warfarin",
    name: "Warfarin",
    primaryUse: "Atrial fibrillation",
    otherUses: ["Venous thromboembolism", "Mechanical heart valves", "Pulmonary embolism"],
    leastResearched: { dimension: "Race", group: "Asian participants" },
    score: 55,
    tier: "Limited",
    components: { age: 69, sex: 62, race: 34 },
    trialCount: 81,
    participantCount: 19402,
    updatedAt: "2025-05-12",
  },
  {
    id: "atorvastatin",
    name: "Atorvastatin",
    primaryUse: "High cholesterol",
    otherUses: ["Cardiovascular risk reduction", "Mixed dyslipidemia"],
    leastResearched: { dimension: "Sex", group: "Female participants" },
    score: 83,
    tier: "Strong",
    components: { age: 84, sex: 76, race: 89 },
    trialCount: 173,
    participantCount: 83410,
    updatedAt: "2025-05-14",
  },
  {
    id: "albuterol",
    name: "Albuterol",
    primaryUse: "Asthma",
    otherUses: ["Exercise-induced bronchospasm", "Chronic obstructive pulmonary disease"],
    leastResearched: { dimension: "Age", group: "Adults 65 and older" },
    score: 68,
    tier: "Developing",
    components: { age: 48, sex: 82, race: 73 },
    trialCount: 117,
    participantCount: 31208,
    updatedAt: "2025-05-11",
  },
  {
    id: "lisinopril",
    name: "Lisinopril",
    primaryUse: "High blood pressure",
    otherUses: ["Heart failure", "Post-heart attack care"],
    leastResearched: { dimension: "Race", group: "Asian participants" },
    score: 73,
    tier: "Developing",
    components: { age: 79, sex: 76, race: 64 },
    trialCount: 102,
    participantCount: 41090,
    updatedAt: "2025-05-13",
  },
  {
    id: "levothyroxine",
    name: "Levothyroxine",
    primaryUse: "Hypothyroidism",
    otherUses: ["Thyroid-stimulating hormone suppression"],
    leastResearched: { dimension: "Sex", group: "Male participants" },
    score: 66,
    tier: "Developing",
    components: { age: 72, sex: 51, race: 68 },
    trialCount: 64,
    participantCount: 12940,
    updatedAt: "2025-05-10",
  },
];
